image:
  - Visual Studio 2019
clone_folder: c:\projects\source


environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

cache:
  - c:\conan\data

before_build:
  - cmd: >-      
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      
      mkdir bin\Release
      
      powershell Compress-Archive -Path src\opengl\opengl_version\res -DestinationPath bin\res.zip
      
      powershell Compress-Archive -Path src -DestinationPath bin\src.zip


build_script:
  - cmd: >-      
      set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
      
      set CONAN_USER_HOME=c:\conan\data
      
      "%PYTHON%" -m pip install --user conan
      
      mkdir build
      
      cmake -S c:\projects\source -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release  
      
      cmake --build ./build --config "Release"

test_script:
  - cmd: cd build && ctest -C Debug

artifacts:
  - path: 'bin/*.*'
    name: Canary

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version ($(APPVEYOR_BUILD_VERSION)). Updated ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true
    on:
      branch: main