image:
  - Visual Studio 2022
clone_folder: c:\projects\source

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

skip_commits:
  files:
    - '*.md'

cache:
  - C:\\projects\\source\\.conan2 -> conanfile.py

before_build:
  - cmd: >-
      "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

      mkdir bin\\Release

      powershell Compress-Archive -Path src\\opengl\\opengl_version\\res -DestinationPath bin\\Release\\res.zip

      powershell Compress-Archive -Path src -DestinationPath bin\\Release\\src.zip

# fonts.zip is now generated after the build process
after_build:
  - cmd: >-
      powershell Compress-Archive -Path fonts -DestinationPath bin\\Release\\fonts.zip

build_script:
  - cmd: >-
      set PATH=%PATH%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python38\\Scripts

      REM Ensure Conan 2.x or newer

      "%PYTHON%" -m pip install --user "conan>=2.0" --upgrade

      REM Set Conan home and detect profiles

      conan config home

      conan profile detect --name windows_msvc > nul 2> nul & exit 0

      REM Install dependencies with Conan using the profiles

      conan profile list

      conan install . -pr windows_msvc -pr:b windows_msvc --build=missing -s compiler.cppstd=23

      REM Check CMake version and list presets

      cmake --version

      cmake --list-presets

      echo Configure and generate build files using the CMake preset

      cmake --preset conan_windows_release-default

      echo Build using msbuild

      cd build

      dir

      msbuild Field-Map-Editor.sln /p:Configuration=Release

      cd ..

      dir /s /b bin\\*.exe

artifacts:
  - path: "bin/Release/*.*"
    name: Canary

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version ($(APPVEYOR_BUILD_VERSION)). Updated ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true
    on:
      branch: main
