image:
  - Visual Studio 2022
clone_folder: c:\projects\source

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

cache:
  - C:\\projects\\source\\.conan2 -> conanfile.py

before_build:
  - cmd: >-
      "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

      mkdir bin\\Release

      powershell Compress-Archive -Path src\\opengl\\opengl_version\\res -DestinationPath bin\\Release\\res.zip

      powershell Compress-Archive -Path src -DestinationPath bin\\Release\\src.zip

build_script:
  - cmd: >-
      set PATH=%PATH%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python38\\Scripts

      REM Ensure Conan 2.x or newer

      "%PYTHON%" -m pip install --user "conan>=2.0" --upgrade

      REM Set Conan home and detect profiles

      conan config home

      conan profile detect --name windows_msvc

      REM Update the profile using Python to ensure correct settings

      "%PYTHON%" -c "import pathlib, re; profile = pathlib.Path('./.conan2/profiles/windows_msvc'); content = profile.read_text(); content = re.sub(r'compiler\\.cppstd=\\d+', 'compiler.cppstd=23', content); profile.write_text(content)"

      REM Install dependencies with Conan using the profiles

      conan profile list

      conan install . -pr windows_msvc -pr:b windows_msvc --build=missing

      REM Check CMake version and list presets

      cmake --version

      cmake --list-presets

      REM Configure and generate build files using the CMake preset

      cmake --preset conan_windows-default

      REM Build using msbuild

      cd build

      msbuild /p:Configuration=Release

after_build:
  - cmd: move bin\\*.exe bin\\Release

test_script:
  - cmd: cd build && ctest -C Debug

artifacts:
  - path: "bin/Release/*.*"
    name: Canary

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version ($(APPVEYOR_BUILD_VERSION)). Updated ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true
    on:
      branch: main
