image:
  - Visual Studio 2019
clone_folder: c:\projects\source

cache:
  - %CONAN_USER_HOME%\conan\data -> conanfile.py, CMakeLists.txt

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

before_build:
  - cmd: mkdir bin\Release
  - cmd: powershell Compress-Archive -Path src\opengl\opengl_version\res -DestinationPath bin\Release\res.zip
  - cmd: powershell Compress-Archive -Path src -DestinationPath bin\Release\src.zip
  - cmd: set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
  - cmd: "%PYTHON%" -m pip install --user conan
  - cmd: mkdir build

build_script:
  - cmd: cmake -S c:\projects\source -B ./build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE:STRING=Release -DCPP_STARTER_USE_IMGUI=ON
  - cmd: cmake --build ./build --config "Release"

test_script:
  - cmd: cd build && ctest -C Debug

artifacts:
  - path: 'bin/Release/*.*'
    name: Canary

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version ($(APPVEYOR_BUILD_VERSION)). Updated ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true
    on:
      branch: main