image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

build_script:
  - cmd: >-
      set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
      "%PYTHON%" -m pip install --user conan
      mkdir build
      cmake --version
      cmake -S c:\projects\source -B build -G "CodeBlocks - NMake Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DCPP_STARTER_USE_IMGUI=ON
      cmake --build build --target all --config "Release"
test_script:
  - cmd: cd build && ctest -C Debug