image:
  - Visual Studio 2022
clone_folder: c:\projects\source
install:
  # Verify current Visual Studio version
  - ps: |
      $vsVersion = & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" /? | Select-String "Version"
      Write-Host "Visual Studio Version: $vsVersion"
  # Try to add MSVC 14.42 toolset (used by v17.14.2)
  - ps: |
      & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --add Microsoft.VisualStudio.Component.VC.14.42.17.14.x86.x64 --quiet --norestart --wait
      if ($LASTEXITCODE -eq 0) { Write-Host "Successfully added MSVC 14.42 toolset" } else { Write-Host "Failed to add MSVC 14.42 toolset, error code: $LASTEXITCODE" }
  # Fallback: Update Visual Studio to v17.14.2 if toolset add fails
  - ps: |
      if ($LASTEXITCODE -ne 0) {
        Write-Host "Attempting to update Visual Studio to v17.14.2"
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" update --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --channelUri https://aka.ms/vs/17/release/17.14.2/channel --quiet --norestart --wait
        if ($LASTEXITCODE -eq 0) { Write-Host "Successfully updated to Visual Studio v17.14.2" } else { Write-Host "Failed to update Visual Studio, error code: $LASTEXITCODE" }
      }
  # Verify compiler version
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cl

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

skip_commits:
  files:
    - '**/*.md'

cache:
  - C:\\projects\\source\\.conan2 -> conanfile.py

before_build:
  - cmd: >-
      "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

      mkdir bin\\Release

      
after_build:
  - cmd: >- 
      dir /s /b bin\\*.exe

      xcopy "res" "bin\\Release\\res" /E /I /Y

      xcopy "fonts" "bin\\Release\\fonts" /E /I /Y

      powershell Compress-Archive -Path bin\\Release\\* -DestinationPath bin\\Release\\Field-Map-Editor_canary_build.zip

      powershell Compress-Archive -Path src -DestinationPath bin\\Release\\src.zip



build_script:
  - cmd: >-
      set PATH=%PATH%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python38\\Scripts

      REM Ensure Conan 2.x or newer

      "%PYTHON%" -m pip install --user "conan>=2.0" --upgrade

      REM Set Conan home and detect profiles

      conan config home

      conan profile detect --name windows_msvc settings.compiler.version=143 > nul 2> nul & exit 0 

      REM Install dependencies with Conan using the profiles

      conan profile list

      conan install . -pr windows_msvc -pr:b windows_msvc --build=missing -s compiler.cppstd=23

      REM Check CMake version and list presets

      cmake --version

      cmake --list-presets

      echo Configure and generate build files using the CMake preset

      cmake --preset conan_windows_release-default

      echo Build using msbuild

      cd build

      dir

      msbuild Field-Map-Editor.sln /p:Configuration=Release

      cd ..

artifacts:
  - path: "bin/Release/Field-Map-Editor_canary_build.zip"
    name: Canary
  - path: "bin/Release/src.zip"
    name: Source

deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version ($(APPVEYOR_BUILD_VERSION)). Updated ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    prerelease: true
    force_update: true
    on:
      branch: main
