image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "C:\\Python38-x64\\python.exe"

build_script:
- cmd: >-
    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts

    "%PYTHON%" -m pip install --user conan==1.40.3

    REM conan config install https://github.com/conan-io/conanclientcert.git

    mkdir build
  
    cmake -S c:\projects\source -B ./build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release -DCPP_STARTER_USE_IMGUI=ON

    cmake --build ./build --config "Release"

test_script:
- cmd: cd build && ctest -C Debug

artifacts:
  - path: 'bin/Release/*.*'
    name: Canary
deploy:
  - provider: GitHub
    release: Canary
    description: Automatic Test build version($(APPVEYOR_BUILD_VERSION)).
    auth_token:
      secure: 5giEwDYEP975x3C+JYDNGukTupBCPcmez7GbulvUX40/2C5cgs5ta8Gyq6IYpFmW
    artifact: Canary
    prerelease: true
    force_update: true