Examples_menu = [ false, false, false, false, false, false, false ]
FF8_menu = [ false, true, true ]
Upscales_menu = [ true, true ]
coo_index = 0
coo_string = 'en'
fields_index = 104
fields_string = 'bcform_1'
paths_index = 0
paths_vector = [
    'D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII Remastered',
    'D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII',
    'D:\games\ff82000',
    'e:\',
    'd:\tim'
]
upscale_paths_index = 0
upscale_paths_vector = [ 'D:\Angelwing-Ultima_Remastered_v1-0-a\field_bg' ]