ff8_directory_paths = [
    'D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII',
    'D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII Remastered',
    'D:\games\ff82000',
    'd:\tim',
    'e:\'
]
selections_path = 'D:\SteamLibrary\steamapps\common\FINAL FANTASY VIII Remastered'